### PR TITLE
[documentation] added commonjs/browserify example (#34)

### PR DESCRIPTION
**Pull request by rachel-carvalho**
As discussed in #39

### CODE REVIEW

**Comment by michaelBenin** [comment]
Could you squash down these commits? LGTM

**Comment by michaelBenin** [comment]
@rachel-carvalho 

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by rachel-carvalho** [comment]
Done! Sorry for the delay, I got caught up with some projects.

**Comment by michaelBenin** [comment]
No prob! 

@lukasolson this LGTM

We should tag and publish this to npm with the updated docs as it's relevant to browserify users. 

Also is this project published to bower?

**Comment by lukasolson** [comment]
@michaelBenin Yes, the project is published in bower.

**Comment by michaelBenin** [comment]
@lukasolson I added you as an owner on npm:

    npm owner add lukasolson backbone-super

**Pull request merged**
